
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  flask:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
