apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flask-app
  region: us-east-1

managedNodeGroups:
  - name: flask-app-node
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    spot: true
